# Generated by Django 4.2.7 on 2023-12-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_profile_rename_artist_user_delete_song_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='Salesperson', max_length=100),
        ),
    ]
