# Generated by Django 4.2.7 on 2023-12-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_user_nationality_remove_user_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='No Position', max_length=100),
        ),
    ]
